name = input("what is your name ? ")
fathername = input("what is your fathername ? ")
mothername = input("what is your mothername ? ")
age = input("what is your age ? ")
grade = input("which grade do you study in ? ")

print("***********************************************")
print(name)
print(fathername)
print(mothername)
print(age)
print(grade)